---
title: C28105 | Документация Майкрософт
ms.custom: ''
ms.date: 11/15/2016
ms.prod: visual-studio-dev14
ms.reviewer: ''
ms.suite: ''
ms.technology:
- vs-devops-test
ms.tgt_pltfrm: ''
ms.topic: article
f1_keywords:
- C28105
helpviewer_keywords:
- C28105
ms.assetid: 5afdec78-30eb-470c-980f-93d0cb3e74cc
caps.latest.revision: 5
author: corob-msft
ms.author: gewarren
manager: ghogen
ms.openlocfilehash: 6b69d84ad48ff83a28dfa2bd172260b7784ba68d
ms.sourcegitcommit: 9ceaf69568d61023868ced59108ae4dd46f720ab
ms.translationtype: MT
ms.contentlocale: ru-RU
ms.lasthandoff: 10/12/2018
ms.locfileid: "49206782"
---
# <a name="c28105"></a>C28105
[!INCLUDE[vs2017banner](../includes/vs2017banner.md)]

Предупреждение C28105: Утечка ресурса вследствие исключения  
  
 Указанный ресурс не освобождается, когда возникает исключение. Инструкция, указанная в пути может вызвать исключение. Это предупреждение аналогично предупреждению [C28103](../code-quality/c28103.md), за исключением того, что в этом случае происходит исключение.  
  
## <a name="example"></a>Пример  
 Следующий пример кода вызывает появление этого предупреждения.  
  
```  
res = KeSaveFloatingPointState(buffer);  
  
res = AllocateResource(Resource);  
char *p2 = new char[10]; // could throw  
  
delete[] p2;  
FreeResource(Resource)  
```  
  
 Следующий пример кода позволяет избежать появления этого предупреждения.  
  
```  
res = AllocateResource(Resource);  
char *p2;  
  
try {  
    p2 = new char[10];  
} catch (std::bad_alloc *e) {  
    // just handle the throw  
    ;  
}  
FreeResource(Resource)  
```



