---
title: C6103 | Документация Майкрософт
ms.custom: ''
ms.date: 2018-06-30
ms.prod: visual-studio-dev14
ms.reviewer: ''
ms.suite: ''
ms.technology:
- vs-devops-test
ms.tgt_pltfrm: ''
ms.topic: article
f1_keywords:
- C6103
ms.assetid: 22d1ab35-31a3-4ba9-8ef4-7a64bce66621
caps.latest.revision: 6
author: corob-msft
ms.author: gewarren
manager: ghogen
ms.openlocfilehash: bb1d8688af4c07fd2b0ee6fe67a56d1387610ff7
ms.sourcegitcommit: 55f7ce2d5d2e458e35c45787f1935b237ee5c9f8
ms.translationtype: MT
ms.contentlocale: ru-RU
ms.lasthandoff: 08/22/2018
ms.locfileid: "47560130"
---
# <a name="c6103"></a>C6103
[!INCLUDE[vs2017banner](../includes/vs2017banner.md)]

Последнюю версию этого раздела можно найти в [C6103](https://docs.microsoft.com/visualstudio/code-quality/c6103).  
  
Предупреждение C6103: возврат \<переменной > сбой вызова функции в строке из \<расположение >.  
  
 Успешный путь через функцию возвращает переменную, которая использовалась как параметр `_Out_` для вызова внутренней функции, завершившегося ошибкой.  
  
 Проблема может заключаться в том, что вызываемая и вызывающая функции не имеют соответствующих примечаний. Вызываемая функция может потребовать `_Always_`, `_Outptr_result_nullonfailure_` (`_COM_Outptr_` для кода COM) или связанное примечание, а вызывающая функция может потребовать примечание `_Success_`. Другая возможная причина этого предупреждения — примечание `_Success_` в вызываемой функции неверное.  
  
## <a name="see-also"></a>См. также  
 [Использование аннотаций SAL для уменьшения количества дефектов в коде C/C++](../code-quality/using-sal-annotations-to-reduce-c-cpp-code-defects.md)



