---
title: C6312 | Документация Майкрософт
ms.custom: ''
ms.date: 2018-06-30
ms.prod: visual-studio-dev14
ms.reviewer: ''
ms.suite: ''
ms.technology:
- vs-devops-test
ms.tgt_pltfrm: ''
ms.topic: article
f1_keywords:
- C6312
helpviewer_keywords:
- C6312
ms.assetid: 1fc8b9a1-e6ba-4799-84c3-31f289576cca
caps.latest.revision: 15
author: corob-msft
ms.author: gewarren
manager: ghogen
ms.openlocfilehash: cbfba91ef4b41c2789713f423db0db3544db045d
ms.sourcegitcommit: 55f7ce2d5d2e458e35c45787f1935b237ee5c9f8
ms.translationtype: MT
ms.contentlocale: ru-RU
ms.lasthandoff: 08/22/2018
ms.locfileid: "47569178"
---
# <a name="c6312"></a>C6312
[!INCLUDE[vs2017banner](../includes/vs2017banner.md)]

Последнюю версию этого раздела можно найти в [C6312](https://docs.microsoft.com/visualstudio/code-quality/c6312).  
  
Предупреждение C6312: возможно, бесконечный цикл: использование константы EXCEPTION_CONTINUE_EXECUTION в выражении фильтра исключений блока try-except  
  
 Это предупреждение указывает на использование константы `EXCEPTION_CONTINUE_EXECUTION` (или другой константы, которая принимает значение -1) в выражении фильтра структурированного обработчика исключений. Использование постоянного значения `EXCEPTION_CONTINUE_EXECUTION` может привести к бесконечному циклу. Например если исключение было вызвано оборудования, будет перезапущена инструкцию, которая вызвала исключение. Если адрес, который вызвал исключение по-прежнему поврежден, другое исключение и обрабатываться таким же образом. Это приводит к бесконечному циклу.  
  
 Явный вызов `RaiseException` не приведет непосредственно к бесконечному циклу, но будет продолжать выполнение кода в защищенном блоке. Это может быть непредвиденным и может привести к бесконечному циклу, если `RaiseException` был использован, чтобы избежать разыменования недопустимый указатель.  
  
 Как правило `EXCEPTION_CONTINUE_EXECUTION` должен возвращаться только функции, вызываемой в критерии фильтра, который имеет возможность устранить либо указатель, который вызвал исключение или основная память.  
  
## <a name="example"></a>Пример  
 В следующем коде создается данное предупреждение:  
  
```  
#include <excpt.h>  
#include <stdio.h>  
#include <windows.h>  
  
void f (char *ptr)  
{  
  __try   
  {  
    // exception occurs if the caller passes null ptr  
    // code...     
   *ptr = '\0';  
  }   
  __except (EXCEPTION_CONTINUE_EXECUTION)  
    // When EXCEPTION_CONTINUE_EXECUTION is used, the handler  
    //  block of the structured exception handler is not executed.   
  {  
    puts("This block is never executed");  
  }  
}  
```  
  
 Чтобы устранить это предупреждение, используйте следующий код:  
  
```  
#include <excpt.h>  
#include <stdio.h>  
#include <windows.h>  
  
void f (char *ptr)  
{  
  __try   
  {  
    // exception occurs if the caller passes null ptr  
    // code...  
    *ptr = '\0';  
  }   
  __except (GetExceptionCode()== EXCEPTION_ACCESS_VIOLATION ?   
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)   
  {  
    puts("Error Occurred");  
  }  
}  
```



