---
title: C6320 | Документация Майкрософт
ms.custom: ''
ms.date: 2018-06-30
ms.prod: visual-studio-dev14
ms.reviewer: ''
ms.suite: ''
ms.technology:
- vs-devops-test
ms.tgt_pltfrm: ''
ms.topic: article
f1_keywords:
- C6320
helpviewer_keywords:
- C6320
ms.assetid: fb9e568e-b3d4-4ce2-a276-a64ad74d7b1e
caps.latest.revision: 12
author: corob-msft
ms.author: gewarren
manager: ghogen
ms.openlocfilehash: f07ca6bdc7300a4029caf272c80d752997884d68
ms.sourcegitcommit: 55f7ce2d5d2e458e35c45787f1935b237ee5c9f8
ms.translationtype: MT
ms.contentlocale: ru-RU
ms.lasthandoff: 08/22/2018
ms.locfileid: "47570659"
---
# <a name="c6320"></a>C6320
[!INCLUDE[vs2017banner](../includes/vs2017banner.md)]

Последнюю версию этого раздела можно найти в [C6320](https://docs.microsoft.com/visualstudio/code-quality/c6320).  
  
предупреждение C6320: выражение фильтра исключений является константой EXCEPTION_EXECUTE_HANDLER. Это может скрыть исключения, не предназначенные для обработки  
  
 Это предупреждение означает использование exception_execute_handler-константа в блока __except побочным эффектом. В данном случае инструкции в \_блок _except всегда будет выполняться для обработки исключения, включая исключения, вы не хотите обрабатывать в определенную функцию. Рекомендуется проверять исключение до его обработки.  
  
## <a name="example"></a>Пример  
 В следующем коде создается данное предупреждение, поскольку блок __except пытается обрабатывать исключения всех типов:  
  
```  
#include <stdio.h>   
#include <excpt.h>   
  
void f(int *p)   
{   
   __try  
   {   
      puts("in try");   
      *p = 13;  // might cause access violation exception  
      // code ...  
   }   
   __except(EXCEPTION_EXECUTE_HANDLER) // warning  
   {   
      puts("in except");   
      // code ...  
   }   
}   
```  
  
 Чтобы устранить это предупреждение, используйте `GetExceptionCode` для проверки для конкретного исключения перед их обработкой, как показано в следующем коде:  
  
```  
#include <stdio.h>   
#include <windows.h>   
#include <excpt.h>   
  
void f(int *p)   
{   
   __try  
   {   
      puts("in try");   
      *p = 13;    // might cause access violation exception   
      // code ...  
   }   
   __except(GetExceptionCode()==EXCEPTION_ACCESS_VIOLATION ?   
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)  
   {   
      puts("in except");   
      // code ...  
   }   
}  
```  
  
## <a name="see-also"></a>См. также  
 [Оператор try-except](http://msdn.microsoft.com/library/30d60071-ea49-4bfb-a8e6-7a420de66381)



