---
title: C6310
ms.date: 11/04/2016
ms.prod: visual-studio-dev15
ms.technology: vs-ide-code-analysis
ms.topic: reference
f1_keywords:
- C6310
helpviewer_keywords:
- C6310
ms.assetid: e759eb63-883f-4c3e-bf2f-b924ff511405
author: mikeblome
ms.author: mblome
manager: wpickett
ms.workload:
- multiple
ms.openlocfilehash: 3b7d3c82ed40f270c9bbe83ba0a0408d50dddcc1
ms.sourcegitcommit: 240c8b34e80952d00e90c52dcb1a077b9aff47f6
ms.translationtype: MT
ms.contentlocale: ru-RU
ms.lasthandoff: 10/23/2018
ms.locfileid: "49837377"
---
# <a name="c6310"></a>C6310
Предупреждение C6310: Недопустимая константа в фильтре исключений может привести к непредвиденному поведению

Это сообщение означает, что в выражении фильтра структурированного обработчика исключений обнаружена недопустимая константа. Используются следующие константы, определенные для использования в выражении фильтра структурированного обработчика исключений:

- `EXCEPTION_CONTINUE_EXECUTION`

- `EXCEPTION_CONTINUE_SEARCH`

- `EXCEPTION_EXECUTE_HANDLER`

Эти значения определяются в excpt.h файл заголовка среды выполнения.

Использование константы, не перечисленные в списке может привести к непредвиденному поведению.

## <a name="example"></a>Пример

В следующем коде создается данное предупреждение:

```cpp
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

BOOL LimitExceeded();

void fd( )
{
  __try
  {
    if (LimitExceeded())
    {
      RaiseException(EXCEPTION_ACCESS_VIOLATION,0,0,0);
    }
    else
    {
      // code
    }
  }
  __except (EXCEPTION_ACCESS_VIOLATION)
  {
    puts("Exception Occurred");
  }
}
```

Чтобы устранить это предупреждение, используйте следующий код:

```cpp
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

BOOL LimitExceeded();

void fd( )
{
  __try
  {
    if (LimitExceeded())
    {
      RaiseException(EXCEPTION_ACCESS_VIOLATION,0,0,0);
    }
    else
    {
      // code
    }
  }
  __except (GetExceptionCode()==EXCEPTION_ACCESS_VIOLATION ?
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)
  {
    puts("Exception Occurred");
  }
}
```