---
title: C6318
ms.date: 11/04/2016
ms.prod: visual-studio-dev15
ms.topic: reference
f1_keywords:
- C6318
helpviewer_keywords:
- C6318
ms.assetid: 3284a83e-bb8e-461c-adcc-cfc66ceea05e
author: mikeblome
ms.author: mblome
manager: wpickett
ms.workload:
- multiple
ms.openlocfilehash: 83dc34d0386101a0840d1283153e072082f6c517
ms.sourcegitcommit: 37fb7075b0a65d2add3b137a5230767aa3266c74
ms.translationtype: MT
ms.contentlocale: ru-RU
ms.lasthandoff: 01/02/2019
ms.locfileid: "53884463"
---
# <a name="c6318"></a>C6318
Предупреждение C6318: Неправильно определенный блок __try /\__except: использование константы EXCEPTION_CONTINUE_SEARCH или другой константы с нулевым результатом в выражении фильтра исключений. Код в блоке обработки исключений не выполняется.

 Это предупреждение указывает, что при возникновении исключения в защищенном блоке обработчика структурированных исключений, исключение не будет обработано, так как константа `EXCECPTION_CONTINUE_SEARCH` используется в выражении фильтра исключений.

 Этот код эквивалентен защищенный блок без блока обработки исключений, так как в блоке обработчика не выполняется.

## <a name="example"></a>Пример
 В следующем коде создается данное предупреждение:

```
#include <excpt.h>
#include <stdio.h>

void f (char *pch)
{
  __try
  {
    // assignment might fail
    *pch = 0;
  }
  __except (EXCEPTION_CONTINUE_SEARCH) // warning 6318
  {
    puts("Exception Occurred");
  }
}
```

 Чтобы устранить это предупреждение, используйте следующий код:

```
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

void f (char *pch)
{
  __try
  {
    // assignment might fail
    *pch = 0;
  }
  __except( (GetExceptionCode() == EXCEPTION_ACCESS_VIOLATION) ?
                EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH )
  {
    puts("Access violation");
  }
}
```

## <a name="see-also"></a>См. также
 [Оператор try-except](/cpp/cpp/try-except-statement)