---
title: C6318
ms.date: 11/04/2016
ms.prod: visual-studio-dev15
ms.technology: vs-ide-code-analysis
ms.topic: reference
f1_keywords:
- C6318
helpviewer_keywords:
- C6318
ms.assetid: 3284a83e-bb8e-461c-adcc-cfc66ceea05e
author: mikeblome
ms.author: mblome
manager: wpickett
ms.workload:
- multiple
ms.openlocfilehash: 73dae483e22b486b9204df97958966e83da66527
ms.sourcegitcommit: e13e61ddea6032a8282abe16131d9e136a927984
ms.translationtype: MT
ms.contentlocale: ru-RU
ms.lasthandoff: 04/26/2018
ms.locfileid: "31895072"
---
# <a name="c6318"></a>C6318
Предупреждение C6318: неправильно определенный блок __try /\__except.: использование константы EXCEPTION_CONTINUE_SEARCH или другой константы, равной нулю в выражении фильтра исключений. Код в блоке обработчика исключений не выполняется

 Это предупреждение означает, что при возникновении исключения в защищенном блоке обработчика структурированных исключений, исключение не будет обработано, так как константа `EXCECPTION_CONTINUE_SEARCH` используется в выражении фильтра исключения.

 Этот код соответствует защищенный блок без блока обработчика исключений, поскольку блок обработки не выполняется.

## <a name="example"></a>Пример
 Это предупреждение возникает в следующем коде:

```
#include <excpt.h>
#include <stdio.h>

void f (char *pch)
{
  __try
  {
    // assignment might fail
    *pch = 0;
  }
  __except (EXCEPTION_CONTINUE_SEARCH) // warning 6318
  {
    puts("Exception Occurred");
  }
}
```

 Чтобы устранить это предупреждение, используйте следующий код:

```
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

void f (char *pch)
{
  __try
  {
    // assignment might fail
    *pch = 0;
  }
  __except( (GetExceptionCode() == EXCEPTION_ACCESS_VIOLATION) ?
                EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH )
  {
    puts("Access violation");
  }
}
```

## <a name="see-also"></a>См. также
 [Оператор try-except](/cpp/cpp/try-except-statement)